sudo: required
services: docker
language: java
jdk: openjdk8
before_script:
- chmod +x gradlew
script:
- ./gradlew build
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
- docker build -t mailcatcher-armhf -f Dockerfile.armhf .
after_success:
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD" 
- docker tag mailcatcher-armhf:latest $DOCKER_USER/mailcatcher-armhf:latest
- docker push $DOCKER_USER/mailcatcher-armhf
env:
  global:
  - secure: LZOhnDyFvuvvldEY3Sger9YU/zRrrteRj/qbtXz1xlodFESnGbUNJ+N7sVYeiqMNR2X1xWaLLhH7Cyc23szf4nhxbZ5cLmuflixX5vXjZ1rhYjErhj8htX7pnUZzg+szFtXYvmm38m3q7ROaUwwMc9z3zLE8RhNYTftOGw258lwcLKhUc2t1Eoa0+CUl5AklVZerCNLCcosGmMZ33017PI2cg0hU7TO4/t9sh2B64eJ6jY2p4LQRwuTBoprAhB/2/N2KD+IEvtbtfECP9bwkjE7b286hwHYUiFjvIbVvFDspdxSWvQq/4moILPnwgfsoFiJkLYW92BhU6xo8yVstStzyq9rgfkP2Nsj+F/SzzCPw9K6G8kOILkK4KUN4/dagXqBSGru5zEzC7T1xPJjRH1LgWHAX9zgQEsmp42DuLDWixpfpT7Keuo0dRMqWJIuXjvcwH7+557pZqgNJHGf+vk9akA4KKE2Ci/akk/9kGR3ERfKmtYePwWiMzZOJ5BLq5B36droNFoO9Jx8xLPuG02HUNJO2FKi3VX2lDSM5LHKNuI54VvwaXzCjxP99tgOD1arJxYX+RybQcND88BLQ9c638HuxG9H1U67tWkzI37WkfJjx+AnNHw7HrBHfc3kuQqv0OJ82mcoDvhfFus0ojNYk3eup5KCTvJcZG00ciHs=
  - secure: kgpYD1ljrhq8LJ8ZC/e04z8On0lgl94Yp0z1ssFb38gAT734IUQiQCQEX3wV8qY7bEgzG1iUKi5WZohjE+KvmZ57PUVi75IWWu4DEtCBgLE0NX0/grIHZHu+k9QvuDPTjob3FLhxMi4uG4EJGC3qxURWDtQnN2wAy2zGyZoXaEu//Guxaz1bm5YS77WL9OgdD9PORx6qkpNBFAVNkkTsHWK7MVnaoEswdX8wcpzTEgVUNj1FT0JufOyTh09gXiyx2mbFRgQK97JpjAxM9v35hug+aFamm21BcnpH9OmrcH75yDdYDh5IF8Ok+vC1FO9A63/T/nxjmmvFtEoleE2Q3JaLucgShHpF4R4M+1Xu0cA+70AqZas/DdSXUbuy7cdqsZHnxkp9jdGXBZVU4sK2fcx71+1LO2jFx95HgZe44QEIsmw7MVgl3bN7ynTSQJydf4ufM09cIIdhSn6YDBUgPA26P0DhS7fjMT1uDGTP/Gjegkbk/4FoLYa9cxHObp1LmRLY9BJkRDZQgrW5DkIpWOFdZ84uQ4yZffEZa2kRGOnF2KOHVt109gB8qPTMHaba/yRszVWmOWYncd2xyBpMlRp/7uejAS4nNmULYrWEa1p66EIQRd1D5dlGa9Ebpd9ylNtfGlqD2b5OAawFRpdS/XcGYHNLy/T4DzpZ0csB4f0=
