FROM arm32v7/openjdk:8-jre

EXPOSE 1025

WORKDIR /appdata
VOLUME /appdata

COPY build/libs/mailcatcher*.jar /opt/mailcatcher.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-jar","/opt/mailcatcher.jar"]

