name: CI Build
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
        id: go

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Upload results to codecov
        uses: codecov/codecov-action@v3

      - name: Check GoReleaser configuration
        uses: goreleaser/goreleaser-action@v2
        with:
          args: check